/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Nz6HQSBUrMP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Card, CardContent } from "@/components/ui/card"

export function Homepage() {
  const [isPlaying, setIsPlaying] = useState(false)
  const [currentSong, setCurrentSong] = useState(null)
  const handlePlayPause = () => {
    setIsPlaying(!isPlaying)
  }
  const handleSkipNext = () => {}
  const handleSkipPrev = () => {}

  return (
    (<div
      className="flex flex-col min-h-screen bg-background text-foreground font-roboto">
      <header className="sticky top-0 z-50 w-full bg-background border-b">
        <div className="container mx-auto px-4 md:px-6 flex items-center h-16">
          <Link href="#" className="mr-6" prefetch={false}>
            <Music2Icon className="h-6 w-6 text-primary" />
            <span className="sr-only">Nagma</span>
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link
              href="#"
              className="text-sm font-medium hover:text-primary"
              prefetch={false}>
              Nagma
            </Link>
          </nav>
          <div className="relative flex-1 max-w-md mx-auto">
            <div
              className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <SearchIcon className="h-5 w-5 text-muted-foreground" />
            </div>
            <Input
              type="search"
              placeholder="Search for songs, artists, and more"
              className="w-full pl-10 pr-4 py-2 rounded-full bg-muted text-foreground focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent" />
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="ml-4">
                <Avatar className="w-8 h-8 rounded-full">
                  <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>John Doe</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>
                <UserIcon className="w-4 h-4 mr-2" />
                Profile
              </DropdownMenuItem>
              <DropdownMenuItem>
                <SettingsIcon className="w-4 h-4 mr-2" />
                Settings
              </DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>
                <LogOutIcon className="w-4 h-4 mr-2" />
                Logout
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-[#9C37F2] text-white py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <Carousel className="max-w-4xl mx-auto">
              <CarouselContent>
                <CarouselItem>
                  <div className="flex flex-col md:flex-row items-center justify-between gap-8">
                    <div className="space-y-4">
                      <h1 className="text-3xl md:text-5xl font-bold tracking-tight">
                        Discover Your Next Favorite Playlist
                      </h1>
                      <p className="text-lg md:text-xl">
                        Explore our curated playlists and find the perfect soundtrack for any mood.
                      </p>
                      <Button
                        className="bg-[#F7EF73] text-[#9C37F2] font-medium px-6 py-3 rounded-full hover:bg-opacity-90"
                        onClick={() => {
                          setCurrentSong({
                            title: "Song Title",
                            artist: "Artist Name",
                            albumArt: "/placeholder.svg",
                          })
                          setIsPlaying(true)
                        }}>
                        Listen Now
                      </Button>
                    </div>
                    <img
                      src="/placeholder.svg"
                      width={400}
                      height={400}
                      alt="Playlist Artwork"
                      className="rounded-2xl object-cover"
                      style={{ aspectRatio: "400/400", objectFit: "cover" }} />
                  </div>
                </CarouselItem>
                <CarouselItem>
                  <div className="flex flex-col md:flex-row items-center justify-between gap-8">
                    <div className="space-y-4">
                      <h1 className="text-3xl md:text-5xl font-bold tracking-tight">
                        Discover Your Next Favorite Playlist
                      </h1>
                      <p className="text-lg md:text-xl">
                        Explore our curated playlists and find the perfect soundtrack for any mood.
                      </p>
                      <Button
                        className="bg-[#F7EF73] text-[#9C37F2] font-medium px-6 py-3 rounded-full hover:bg-opacity-90"
                        onClick={() => {
                          setCurrentSong({
                            title: "Song Title",
                            artist: "Artist Name",
                            albumArt: "/placeholder.svg",
                          })
                          setIsPlaying(true)
                        }}>
                        Listen Now
                      </Button>
                    </div>
                    <img
                      src="/placeholder.svg"
                      width={400}
                      height={400}
                      alt="Playlist Artwork"
                      className="rounded-2xl object-cover"
                      style={{ aspectRatio: "400/400", objectFit: "cover" }} />
                  </div>
                </CarouselItem>
              </CarouselContent>
              <CarouselPrevious />
              <CarouselNext />
            </Carousel>
          </div>
        </section>
        <section className="py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <div className="mb-8 md:mb-12">
              <h2 className="text-2xl md:text-3xl font-bold text-atlantic-bc">Recommended for You</h2>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-8">
              <Card
                className="bg-muted rounded-2xl overflow-hidden"
                onClick={() => {
                  setCurrentSong({
                    title: "Song Title",
                    artist: "Artist Name",
                    albumArt: "/placeholder.svg",
                  })
                  setIsPlaying(true)
                }}>
                <CardContent className="p-4">
                  <img
                    src="/placeholder.svg"
                    width={200}
                    height={200}
                    alt="Album Art"
                    className="rounded-xl w-full h-auto object-cover"
                    style={{ aspectRatio: "200/200", objectFit: "cover" }} />
                  <div className="mt-4 space-y-1">
                    <h3 className="text-lg font-bold text-atlantic-bc">Song Title</h3>
                    <p className="text-sm text-muted-foreground">Artist Name</p>
                    <Button variant="ghost" size="icon" className="ml-auto">
                      <PlayIcon className="h-6 w-6 text-primary" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 bg-muted">
          <div className="container mx-auto px-4 md:px-6">
            <div className="mb-8 md:mb-12">
              <h2 className="text-2xl md:text-3xl font-bold text-atlantic-bc">Curated Playlists</h2>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-8">
              <Card
                className="bg-background rounded-2xl overflow-hidden"
                onClick={() => {
                  setCurrentSong({
                    title: "Song Title",
                    artist: "Artist Name",
                    albumArt: "/placeholder.svg",
                  })
                  setIsPlaying(true)
                }}>
                <CardContent className="p-4">
                  <img
                    src="/placeholder.svg"
                    width={200}
                    height={200}
                    alt="Playlist Artwork"
                    className="rounded-xl w-full h-auto object-cover"
                    style={{ aspectRatio: "200/200", objectFit: "cover" }} />
                  <div className="mt-4 space-y-1">
                    <h3 className="text-lg font-bold text-atlantic-bc">Playlist Title</h3>
                    <p className="text-sm text-muted-foreground">Playlist Description</p>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <div className="mb-8 md:mb-12">
              <h2 className="text-2xl md:text-3xl font-bold text-atlantic-bc">Popular Artists</h2>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-8">
              <Card className="bg-muted rounded-2xl overflow-hidden">
                <CardContent className="p-4 flex flex-col items-center">
                  <Avatar className="w-20 h-20 rounded-full">
                    <AvatarImage src="/placeholder-user.jpg" alt="Artist Avatar" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <h3 className="mt-4 text-lg font-bold text-atlantic-bc">Artist Name</h3>
                  <Link
                    href="#"
                    className="text-sm text-primary hover:underline"
                    prefetch={false}>
                    View Profile
                  </Link>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      {currentSong && (
        <div
          className="fixed bottom-0 left-0 w-full bg-background border-t shadow-lg z-50 px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <img
              src="/placeholder.svg"
              width={50}
              height={50}
              alt="Album Art"
              className="rounded-md"
              style={{ aspectRatio: "50/50", objectFit: "cover" }} />
            <div>
              <h3 className="font-bold text-lg">{currentSong.title}</h3>
              <p className="text-muted-foreground">{currentSong.artist}</p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon" onClick={handleSkipPrev}>
              <SkipBackIcon className="h-6 w-6" />
            </Button>
            <Button variant="ghost" size="icon" onClick={handlePlayPause}>
              <PauseIcon className="h-6 w-6" />
            </Button>
            <Button variant="ghost" size="icon" onClick={handleSkipNext}>
              <SkipForwardIcon className="h-6 w-6" />
            </Button>
          </div>
        </div>
      )}
    </div>)
  );
}

function LogOutIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>)
  );
}


function Music2Icon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="8" cy="18" r="4" />
      <path d="M12 18V2l7 4" />
    </svg>)
  );
}


function PauseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect x="14" y="4" width="4" height="16" rx="1" />
      <rect x="6" y="4" width="4" height="16" rx="1" />
    </svg>)
  );
}


function PlayIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function SettingsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}


function SkipBackIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon points="19 20 9 12 19 4 19 20" />
      <line x1="5" x2="5" y1="19" y2="5" />
    </svg>)
  );
}


function SkipForwardIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon points="5 4 15 12 5 20 5 4" />
      <line x1="19" x2="19" y1="5" y2="19" />
    </svg>)
  );
}


function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}
